### PR TITLE
Rewrite the edala scraper so php isn't needed as a CGI anymore

### PR DESCRIPTION
**Pull request by CloCkWeRX**

### CODE REVIEW

**Comment by henare** [comment]
The EDALA scraper is working so I'm not going to merge this right now. It will probably be useful in the not too distant future but right now I think it's good to have a working PHP example anyway.

**Comment by henare** [comment]
Moving this on to Morph would be the way to go with this. Fancy doing that @CloCkWeRX?

**Comment by CloCkWeRX** [comment]
Can do,  but traveling for next few weeks - hard to find time

**Comment by mlandauer** [comment]
@CloCkWeRX it's okay. The dirty deed is done. The edala scraper now lives at https://morph.io/planningalerts-scrapers/edala

**Pull request closed without merging**
