### PR TITLE
Charles Sturt scraper

### PR DESCRIPTION
**Pull request by CloCkWeRX**
Here's a shot at merging in barossa/charles sturt council scrapers; and comments about other eproclaim systems. I understand you've already merged the burnside changes

### CODE REVIEW

**Comment by henare** [comment]
Thanks @CloCkWeRX.

The City of Charles Sturt includes the on_notice_to date in their data. This is used by PlanningAlerts to say "you have X number of days to respond to this application" and with our new commenting feature this is reasonably important. Can you take a look at adding this to the scraped data?

With the Barossa one I wasn't able to find any DAs so I wasn't able to test it. Can you let me know how you tested it so I can replicate it locally?

**Comment by CloCkWeRX** [comment]
Unfortunately I couldn't see any barossa DA's either. I was assuming that they are on the same version of eproclaim as charles sturt; but I can disable this scraper if you want

**Comment by henare** [comment]
I think we should hold off until there is data for Barossa.

It looks like you've finished City of Charles Sturt though, am I OK to merge and deploy it?

**Comment by CloCkWeRX** [comment]
Go for it

**Comment by henare** [comment]
A couple of problems - when I click on an info_url I get a page that says, "Oops, this site is currently unavailable due to a communications outage.". Can you work out an info_url that'd be useful to the user if they click "read more" on PlanningAlerts. If you can link directly to the DA, see if you can link to the list or a search page.

Also, comment_url isn't populated. Can you track down a way for us to comment on the DAs? An email address for the council in a mailto link is fine.

Thanks!

**Comment by CloCkWeRX** [comment]
How annoying: I fixed the URL but unless you go in via the frames and get a cookie; URLs like:
https://ipa.charlessturt.sa.gov.au/eproclaim/ptgeApplications/ptgeApplicationOverview.asp?table_no=250894
... just won't work.

**Comment by henare** [comment]
It's ridiculously common with these crap sites.

**Comment by CloCkWeRX** [comment]
Stupid buttons.

So; the only way I have to fix this: some kind of frame page that loads https://ipa.charlessturt.sa.gov.au/eproclaim/ptgeSessionPersist.asp then loads the development application url. That sounds messy.

It's like this system hates the web - you'll never see this applications in google with this cookie stuff.

Ironically the site itself touches on the intent to be open and transparent; it's just the tools they use are making it hard.

Comment email doesn't appear to be a valid method of input either:
Applications may be examined at the Civic Centre, 72 Woodville Road during normal business hours, and any person affected may make relevant representations in writing to reach the Chief Executive no later than the Closing Date and Time specified above. 
Each person making a submission should indicate whether that person wishes to appear personally, or be represented by another party, before the Charles Sturt Development Assessment Panel in support of their submission. 
Please note that, pursuant to Section 38(8) of the Development Act, a copy of each representation received will be forwarded to the applicant for a written response.

I'll get a work friend who's actually a rate payer in that council area to find out if there's better ways to talk to them about development applications.

**Comment by henare** [comment]
I normally just try to find out the planning email and failing that the
general email address; we use an email address to enable commenting these
days.

**Comment by henare** [comment]
Since we now [prefer scrapers on ScraperWiki](http://www.planningalerts.org.au/how_to_write_a_scraper), I hope you don't mind me closing this PR and asking you to move these onto ScraperWiki @CloCkWeRX?

Once they're on there just let us know and we can easily add them to PlanningAlerts.

**Pull request closed without merging**
