### PR TITLE
ScraperWiki

### PR DESCRIPTION
**Pull request by henare**

### CODE REVIEW

**Comment by henare** [comment]
One issue with this approach so far is that these scrapers are designed differently to our local scrapers and can take ages to run, see issue opened here: https://tickets.openaustraliafoundation.org.au/browse/PA-460

**Comment by henare** [comment]
This is seriously broken, we need to incorporate scraperwiki/scraperwiki-ruby#18 and add some tests here I think.

**Comment by CloCkWeRX** [comment]
I've split specific issues off for each of the mentioned scraperwiki parsers - we can keep/kill individually.

**Comment by CloCkWeRX** [comment]
:/ scraperwiki classic is quite dead looking at the moment - now I can't even get the disk full errors, they've obviously disabled something.

**Comment by mlandauer** [comment]
Can we close this PR without merging?

**Comment by henare** [comment]
If everything is on Morph, yes we can.

**Pull request closed without merging**
