### PR TITLE
Rewrite the Ballina scraper in ruby

### PR DESCRIPTION
**Pull request by CloCkWeRX**

### CODE REVIEW

**Comment by henare** [comment]
The PHP one is still working and we're using it until we move from ScraperWiki so I'll hold off merging this for the moment.

**Comment by mlandauer** [comment]
The php scraper for Ballina is now running on Morph too. So, I think I'll just leave this too for the time being

**Comment by henare** [comment]
Since this is on Morph we should delete it from this repo.

**Comment by henare** [comment]
Duh, it was already on ScraperWiki so ignore my last comment.

**Pull request closed without merging**
